### ISSUE TITLE
Add write permissions in actions

### ISSUE THREAD

**Issue by dieghernan** [rOpenGov/rogtemplate#12]
See https://github.com/rOpenGov/nasa/issues/1:

```yaml

... 

jobs:
  rogtemplate-gh-pages:
    runs-on: ubuntu-latest
    permissions: write-all # <- Add here
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4

... 

```
